name: ios_simulator_flutter_web
description: A Flutter web app that simulates an iPhone and loads a Flutter app.

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.1
  firebase_core: ^3.15.1
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/background1.jpg
    - assets/screenshots/catalog_1.png
    - assets/screenshots/catalog_2.png
    - assets/screenshots/catalog_3.png
    - assets/screenshots/catalog_4.png
    - assets/screenshots/dday_1.png
    - assets/screenshots/dday_2.png
    - assets/screenshots/dday_3.png
    - assets/screenshots/dday_4.png
    - assets/screenshots/sim_1.png
    - assets/screenshots/sim_2.png
    - assets/screenshots/sim_3.png
    - assets/screenshots/sim_4.png
    # - assets/Tanmay_Resume.pdf
    # - assets/Tanmay_Resume1.pdf
    # - assets/Tanmay_Kumar.pdf
